[package]
name = "nb-utils"
version = "0.2.0"
authors = ["Aleksei Sidorov <gorthauer87@yandex.ru>"]
edition = "2021"

[dependencies]
nb = "1.0"
futures-util = { version ="0.3", default-features = false }

[dev-dependencies]
spin_on = "0.1.1"

[features]
std = []
